### ISSUE TITLE
better to split non-core features out to separate distributions?

### ISSUE THREAD

**Issue by iynehz** [ronsavage/GraphViz2#6]
For "non-core features" I mean modules like GraphViz2::DBI and GraphViz2::Parse::X. Now this GraphViz2 distribution has a lot dependencies, installing GraphViz2 gets a lot packages installed. That is IMHO suboptimal for users who just want the core GraphViz2 module not GraphViz2::DBI or GraphViz2::Parse::X...

**Comment by ronsavage** [comment]
Hi

Understand. But it would be confusing for beginners expecting those 
sub-modules and not getting them. And confusing if some modules got 
upgraded and some didn't. The suggestion needs more thought.

---
Cheers
Ron
savage.net.au

**Comment by mohawk2** [comment]
This is exactly the same problem faced by PDL (hi @stphnlyd!), which I've been considering for the last 5+ years. It's also one I identified myself when installing it myself this week on a new Perl. One possibility is to downgrade all the gold-plated extra dependencies from "requires" to "recommends", and have the tests skip if not present.

I believe Ron is describing a problem of beginners' expectations. My feeling is those expectations would not exist if the more-specific modules were released (with suitable version numbers of 2.49+ given the latest is now 2.48) first, then a stripped-down GraphViz2 version 2.49 were released without the extras, but with loud docs at the top saying the extras exist.

Not only is this a smaller install for those who just want GraphViz2 and nothing else, it's also much less of a maintenance nightmare (which PDL still suffers from until I start bringing the experimental splitting in PDLA back in to PDL, in a suitably cautious manner of course).

@ronsavage Are you content for me to proceed with this, or do you object? :-)

**Comment by ronsavage** [comment]
Hi Ed

I find this issue hard to resolve. That's why I've never acted on it. 
What worries me is the attitude behind the suggestion. Is it a type of 
fanaticism which wants the main distro to be a small and clean as 
possible? I suspect and fear that to be the case :-((. And really, what 
is the gain?

Then there is the new problem of whether or not to keep the version 
numbers up-to-date (ie the same) in all distros.

And if we adopt your suggestion of adding from_port and to_port to 
add_edge(), how many of those other distros would need updating? None? 
But what if a user then assumes the other distros also now accept 
from_port/to_port? I did not check them to see if this is a plausible 
scenario, but I certainly don't was incompatibilities between distros!

And is there a risk that someone could install the new, small distro 
without realizing they are not getting the other distros? If those other 
distros have not changed, there is no risk of course. But it's just more 
effort to install a set of distros. And I certainly don't want to create 
doubt in the minds of users that by installing the new, small distro 
that they are somehow missing out on updates to the other distros. IOW I 
feel the possible confusion is worse than the tiny effort of installing 
a larger distro.

---
Cheers
Ron
savage.net.au

**Comment by iynehz** [comment]
@ronsavage 

> Is it a type of fanaticism which wants the main distro to be a small and clean as possible? I suspect and fear that to be the case :-((. And really, what is the gain?

I don't think it necessarily has to be the very "minimal possible" main distro. The granularity depends on how the components relate to each other, what each of them depends on, and how each of them could evolve in future. After all the possible gain in decoupling the non-core features are basically clearer/easier dependencies management and component maintenance. 

So the "core" distro may still bundle some of the extra features, and the "extra" distros can usually be what are, 
- very loosely related to the core feature 
- less used together with the main feature
- easier maintained separately

In terms of dependencies management, more dependencies adds the to chance of installation failure, and in some cases it adds to the effort to troubleshoot things. At my workplace we need to explicitly specify/install the whole list of (direct and indirect) dependencies (of course we have some tool to resolve that), but then I was surprised to find this library depends on such a long list of other packages most of which are not really necessary. I was only using the core feature, like I don't really need DBI/DBIx::Class/etc.

And in terms of development/release, if a non-core feature is split out, it could be easier to maintain it separately, like you don't have to maintain/release it together with the core distro. You can release it in a much faster frequency than how you release the main distro. So, 

> there is the new problem of whether or not to keep the version numbers up-to-date (ie the same) in all distros.

My answer to this question is: No you don't have to make them on exactly the same version. Some people's practice is adopting some semver control, say the core distro is 2.481000 (or v2.481.0), then the extra distros that are compatible with it can be 2.481xxx (or v 2.481.xxx), when you make some incompatible change in the core distro, you bump the extra distros. If you bump the core distro to 2.482 but without break the compatibility, you may or may not bump the extra distros. 

> And is there a risk that someone could install the new, small distro without realizing they are not getting the other distros

I think if user follow the common practice of using dependencies in the Perl world, then they can  avoid running into this situation: When I use GraphViz2::DBI in my code, I should ideally specify my dependency on this GraphViz2::DBI module, rather than just GraphViz2. And as long as I am doing it this way, I am not affected if GraphViz2::DBI is bundled or is separate from Graphviz2.

**Comment by ronsavage** [comment]
Hi Stphnlyd

Well argued! I'm coming round to the idea of separate distros.

What do you think of - for one thing - putting GraphViz2::Parse::* in one distro?

**Comment by mohawk2** [comment]
I did an investigation: all the CPAN distros depending on GraphViz2 only actually use the top-level class.

My suggested strategy (as pursued with PDLA) is to split by external dep. If the `GraphViz2::Parse::*` code all depends on the same thing(s), that would be one distro. I haven't looked at the specifics of the split yet, because there's no point until Ron, the author of this beast, gives his blessing :-)

**Comment by mohawk2** [comment]
Good news, everyone!

I've just released GraphViz2::DBI as a standalone distro, and stripped out its deps (DBI etc) from the main GraphViz2. The main CI has gone from taking about 1:45 to about 1:21. It seems reasonable to believe that a similar speedup (especially given the installing of Perl itself is quite an overhead) will be enjoyed by those installing GraphViz2 once I finish the splitting, and release a cut-down version.

**Comment by mohawk2** [comment]
I have now released as their own distro, all v2.49: GraphViz2::DBI, GraphViz2::Parse::XML, GraphViz2::Parse::ISA, GraphViz2::Data::Grapher, GraphViz2::Parse::RecDescent. I also zapped the use of Capture::Tiny since it also was using IPC::Run3. Now the CI runs in just under a minute.

I have just released GraphViz2 2.49, which now has about 10 deps instead of about 35 (some of the deps were only used to generate the website). Please give it a go (especially on a clean Perl) and see what you think!

**Comment by iynehz** [comment]
@mohawk2 @ronsavage awesome thanks!

**Comment by mohawk2** [comment]
Very welcome! 2.54 now has only 5 deps.

**Comment by mohawk2** [comment]
For a nice bit of visualisation of deps as a graph (how appropriate!), compare the dependencies of the last version before I started dropping deps (https://cpandeps.grinnz.com/?dist=GraphViz2&dist_version=2.47) with the current (https://cpandeps.grinnz.com/?dist=GraphViz2&dist_version=2.47). I don't think we have a module to do that with GraphViz2 yet, we probably should.

**Comment by ronsavage** [comment]
Hi

Wow.  Beautiful. I assume there was a typo in your email and that the 
2nd link should have read:
https://cpandeps.grinnz.com/?dist=GraphViz2&dist_version=2.52

---
Cheers
Ron
savage.net.au

**Comment by ronsavage** [comment]
Hi Ed

Oops. I should have referred to 2.54. Mea culpa.

---
Cheers
Ron
savage.net.au

**Comment by mohawk2** [comment]
In fact, just leaving off the version would have loaded current (2.54), which is what I meant to do. Oh well!
