### ISSUE TITLE
Run a gvpr script?

### ISSUE THREAD

**Issue by jhannah-mm** [ronsavage/GraphViz2#9]
Just curious if there'd by any interest it adding functionality or documentation around using `gvpr` as a step in Perl programs. I think I'm in this exact situation: https://stackoverflow.com/questions/7355241/pruning-large-graphs-of-stray-nodes

And it might be cool to have method(s) or doc(s) for how I can trivially run arbitrary `gvpr` scripts against the `$graph` I've built up in Perl, and then happily continue doing my thing in Perl space?

**Comment by ronsavage** [comment]
Hi Jay

Have you seen this page: 
https://savage.net.au/Perl-modules/html/graphviz2.marpa.pathutils/?

The link stars on this page: 
http://savage.net.au/Module-reviews.html#Output_from_my_Graphviz_oriented_modules.

HTH.

---
Cheers
Ron
savage.net.au

**Comment by mohawk2** [comment]
The idiomatic approach for GraphViz2 would be to not use GraphViz2 for that, because GraphViz2 is supposed to take inputs, and visualise them. Instead, you would load your graph data into a [Graph](https://metacpan.org/pod/Graph) object. You could then manipulate that object in Perl, then maybe "graphvizify" it (see the `from_graph` docs, or [an example `graphvizify` function](https://metacpan.org/pod/GraphViz2::Parse::STT#graphvizify)), then pass it to the relatively-new [`GraphViz2->from_graph`](https://metacpan.org/pod/GraphViz2#from_graph) method.

For the situation in the SO question, you would probably want to do a [depth-first search](https://metacpan.org/pod/Graph::Traversal), tracking a "depth" counter, and marking as "keep" all vertices which show a depth >= 3. Then you would delete all vertices not marked as "keep". If you have 35k vertices, you probably don't want to use the `for_shortest_paths` method, because that first makes a transitive closure, which is currently only uses Floyd-Warshall, which is O(V^3) in time and O(V^2) in memory.

With regards to Ron's Marpa modules, they probably want to gain functionality to produce Graph objects. PRs welcome!

Please let us know on here how you get on, because it would be interesting to capture your approach in the docs, and maybe even on that SO question.

**Comment by jhannah-mm** [comment]
Thank you both, I've learned a lot reading your messages, links.
I apologize to you both: The problem I'm having isn't the SO problem. What I'm trying to accomplish in Perl space (if practical) is to throw away all nodes that aren't connected to 2+ other nodes. For example:
```
use Graph::Directed;
use Graph::Writer::Dot;
my $g = Graph::Directed->new;
$g->add_edge(1,2);
$g->add_edge(2,3);
$g->add_edge(4,5);
$g->add_vertex(6);
my $writer = Graph::Writer::Dot->new();
$writer->write_graph($g, 'demo.dot');
```
Goal: 4, 5, 6 are thrown away because they're not connected enough.
Ideally I would then send each cluster that didn't get thrown away to a GraphViz `.png`. :)

**Comment by jhannah-mm** [comment]
By generating the above `.dot` file I can then use [NetworkX](https://networkx.org/) (Python) to pull all `len(f) >= 5` (for example). Demo my buddy wrote that works: https://github.com/payne/DisconnectedGraphs/blob/master/print_connected_components.py

I'm guessing Perl can do this too but I don't know how. Apologies I've strayed so far from the original ask of this Issue (and from Graphviz).

**Comment by ronsavage** [comment]
Hi Jay

No need to apologise. It was a wise decision to ask for help in such as 
situation.

---
Cheers
Ron
savage.net.au

**Comment by jhannah-mm** [comment]
Oh yay! I got it! Who needs Python? ;)  Thanks for your help!
```use Graph::Directed;
use GraphViz2;
my $g = Graph::Directed->new;
$g->add_edges(qw( 1 2 2 3 4 5 ));
$g->add_vertex(6);
# Discard all subgraphs that have < 3 vertices 
my @wcc = $g->weakly_connected_components;
foreach my $wcc (@wcc) {
  if (scalar(@$wcc) < 3) {
    foreach my $v (@$wcc) {
      $g->delete_vertex($v);
    }
  }
}
GraphViz2->from_graph($g)->run(format => 'png', output_file => 'demo.png');
```

**Comment by mohawk2** [comment]
@jhannah-mm Great work! Why not add that as an answer on the SO question, at least as a starter of real, working code for a related problem?

**Comment by jhannah-mm** [comment]
@mohawk2 I was too tired when reading SO apparently, my question / solution wasn't relevant to his question at all. :)

**Comment by mohawk2** [comment]
Good reason ;-)
